function filenm = gen_niifilename(xrange,yrange,zrange,imageToken,appendName)

filenm = [imageToken, '_x', int2str(xrange(1)), '-', int2str(xrange(2)), ...
                   '_y', int2str(yrange(1)), '-', int2str(yrange(2)), ...
                   '_z', int2str(zrange(1)), '-', int2str(zrange(2)), ...
                   '_r0_', appendName];
end